import { MockVariant } from "../respond";
import { MsgError, PensionStatementsSuccess } from "../../types";

/**
 * Response shapes of POST PensionersApp/v1/pension-statements (pension
 * statement PDF + per-period payment rows). `base64` is a placeholder PDF;
 * replace freely with any small valid PDF base64.
 */
export const PENSION_STATEMENTS_VARIANTS = {
  /** 200 — full statement: encoded PDF plus all payment rows. */
  success: {
    status: 200,
    body: {
      base64:
        "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA1OTUgODQyXSAvQ29udGVudHMgNCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNSAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA0OCA+PgpzdHJlYW0KQlQgL0YxIDE2IFRmIDcyIDcwMCBUZCAoUGVuc2lvbiBTdGF0ZW1lbnQpIFRqIEVUCmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iago8PCAvVHlwZSAvRm9udCAvU3VidHlwZSAvVHlwZTEgL0Jhc2VGb250IC9IZWx2ZXRpY2EgPj4KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwMzM5IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDA5CiUlRU9GCg==",
      data: [
        {
          date_frm: "Jul-22",
          date_to: "Jul-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "6725",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "34625",
          ddo_bill_date: "8/3/22",
        },
        {
          date_frm: "Aug-22",
          date_to: "Aug-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "6725",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "34625",
          ddo_bill_date: "9/1/22",
        },
        {
          date_frm: "Sep-22",
          date_to: "Sep-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "6725",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "34625",
          ddo_bill_date: "10/3/22",
        },
        {
          date_frm: "Sep-22",
          date_to: "Sep-22",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "2421",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "2421",
          ddo_bill_date: "10/25/22",
        },
        {
          date_frm: "Oct-22",
          date_to: "Oct-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "7532",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "35432",
          ddo_bill_date: "11/1/22",
        },
        {
          date_frm: "Nov-22",
          date_to: "Nov-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "7532",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "35432",
          ddo_bill_date: "12/1/22",
        },
        {
          date_frm: "Nov-22",
          date_to: "Nov-22",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "887700",
          comm_gross: "0",
          deduction: "0",
          net_amt: "887700",
          ddo_bill_date: "12/6/22",
        },
        {
          date_frm: "Dec-22",
          date_to: "Dec-22",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "7532",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "35432",
          ddo_bill_date: "12/22/22",
        },
        {
          date_frm: "Dec-22",
          date_to: "Dec-22",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "6456",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "6456",
          ddo_bill_date: "1/3/23",
        },
        {
          date_frm: "Jan-23",
          date_to: "Jan-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "8608",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "36508",
          ddo_bill_date: "2/1/23",
        },
        {
          date_frm: "Feb-23",
          date_to: "Feb-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "8608",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "36508",
          ddo_bill_date: "3/1/23",
        },
        {
          date_frm: "Mar-23",
          date_to: "Mar-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "8608",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "36508",
          ddo_bill_date: "4/6/23",
        },
        {
          date_frm: "Apr-23",
          date_to: "Apr-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "8608",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "36508",
          ddo_bill_date: "5/1/23",
        },
        {
          date_frm: "May-23",
          date_to: "May-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "8608",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "36508",
          ddo_bill_date: "6/1/23",
        },
        {
          date_frm: "May-23",
          date_to: "May-23",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "5380",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "5380",
          ddo_bill_date: "6/16/23",
        },
        {
          date_frm: "Jun-23",
          date_to: "Jun-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "7/3/23",
        },
        {
          date_frm: "Jul-23",
          date_to: "Jul-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "8/1/23",
        },
        {
          date_frm: "Aug-23",
          date_to: "Aug-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "9/1/23",
        },
        {
          date_frm: "Sep-23",
          date_to: "Sep-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "10/3/23",
        },
        {
          date_frm: "Oct-23",
          date_to: "Oct-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "11/1/23",
        },
        {
          date_frm: "Nov-23",
          date_to: "Nov-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "12/1/23",
        },
        {
          date_frm: "Dec-23",
          date_to: "Dec-23",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "9684",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "37584",
          ddo_bill_date: "12/21/23",
        },
        {
          date_frm: "Dec-23",
          date_to: "Dec-23",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "4842",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "4842",
          ddo_bill_date: "1/23/24",
        },
        {
          date_frm: "Jan-24",
          date_to: "Jan-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "10491",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "38391",
          ddo_bill_date: "2/1/24",
        },
        {
          date_frm: "Feb-24",
          date_to: "Feb-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "10491",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "38391",
          ddo_bill_date: "3/1/24",
        },
        {
          date_frm: "Mar-24",
          date_to: "Mar-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "10491",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "38391",
          ddo_bill_date: "4/1/24",
        },
        {
          date_frm: "Mar-24",
          date_to: "Mar-24",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "3228",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "3228",
          ddo_bill_date: "4/16/24",
        },
        {
          date_frm: "Apr-24",
          date_to: "Apr-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "5/1/24",
        },
        {
          date_frm: "May-24",
          date_to: "May-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "6/3/24",
        },
        {
          date_frm: "Jun-24",
          date_to: "Jun-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "7/1/24",
        },
        {
          date_frm: "Jul-24",
          date_to: "Jul-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "8/1/24",
        },
        {
          date_frm: "Aug-24",
          date_to: "Aug-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "9/2/24",
        },
        {
          date_frm: "Sep-24",
          date_to: "Sep-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "10/1/24",
        },
        {
          date_frm: "Oct-24",
          date_to: "Oct-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "11567",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "39467",
          ddo_bill_date: "11/4/24",
        },
        {
          date_frm: "Oct-24",
          date_to: "Oct-24",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "3228",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "3228",
          ddo_bill_date: "11/21/24",
        },
        {
          date_frm: "Nov-24",
          date_to: "Nov-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "12374",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "40274",
          ddo_bill_date: "12/2/24",
        },
        {
          date_frm: "Dec-24",
          date_to: "Dec-24",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "12374",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "40274",
          ddo_bill_date: "12/19/24",
        },
        {
          date_frm: "Jan-25",
          date_to: "Jan-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "12374",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "40274",
          ddo_bill_date: "2/1/25",
        },
        {
          date_frm: "Feb-25",
          date_to: "Feb-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "12374",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "40274",
          ddo_bill_date: "3/1/25",
        },
        {
          date_frm: "Mar-25",
          date_to: "Mar-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "12374",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "40274",
          ddo_bill_date: "4/1/25",
        },
        {
          date_frm: "Mar-25",
          date_to: "Mar-25",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "2421",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "2421",
          ddo_bill_date: "4/22/25",
        },
        {
          date_frm: "Apr-25",
          date_to: "Apr-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "5/1/25",
        },
        {
          date_frm: "May-25",
          date_to: "May-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "6/1/25",
        },
        {
          date_frm: "Jun-25",
          date_to: "Jun-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "7/1/25",
        },
        {
          date_frm: "Jul-25",
          date_to: "Jul-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "8/1/25",
        },
        {
          date_frm: "Aug-25",
          date_to: "Aug-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "9/1/25",
        },
        {
          date_frm: "Sep-25",
          date_to: "Sep-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "9/29/25",
        },
        {
          date_frm: "Oct-25",
          date_to: "Oct-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13181",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41081",
          ddo_bill_date: "11/1/25",
        },
        {
          date_frm: "Oct-25",
          date_to: "Oct-25",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "2152",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "2152",
          ddo_bill_date: "11/11/25",
        },
        {
          date_frm: "Nov-25",
          date_to: "Nov-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "12/1/25",
        },
        {
          date_frm: "Dec-25",
          date_to: "Dec-25",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "12/19/25",
        },
        {
          date_frm: "Jan-26",
          date_to: "Jan-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "2/2/26",
        },
        {
          date_frm: "Feb-26",
          date_to: "Feb-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "3/1/26",
        },
        {
          date_frm: "Mar-26",
          date_to: "Mar-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "4/10/26",
        },
        {
          date_frm: "Apr-26",
          date_to: "Apr-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "5/1/26",
        },
        {
          date_frm: "May-26",
          date_to: "May-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "6/1/26",
        },
        {
          date_frm: "Jun-26",
          date_to: "Jun-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "13719",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "41619",
          ddo_bill_date: "6/24/26",
        },
        {
          date_frm: "Jun-26",
          date_to: "Jun-26",
          no_of_months: "1",
          bp: "0",
          dp: "0",
          da: "0",
          ma: "0",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "3228",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "3228",
          ddo_bill_date: "7/1/26",
        },
        {
          date_frm: "Jul-26",
          date_to: "Jul-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "14257",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "42157",
          ddo_bill_date: "7/28/26",
        },
        {
          date_frm: "Aug-26",
          date_to: "Aug-26",
          no_of_months: "1",
          bp: "26900",
          dp: "0",
          da: "14257",
          ma: "1000",
          age_bonus: "0",
          wa: "0",
          dra: "0",
          oth: "0",
          arr_gross: "0",
          gra_gross: "0",
          comm_gross: "0",
          deduction: "0",
          net_amt: "42157",
          ddo_bill_date: "8/27/26",
        },
      ],
    },
  },
  /** Missing/invalid request → generic outer-handler failure. */
  failure: { status: 400, body: { msg: " (Unable to process)" } },
} satisfies Record<string, MockVariant<PensionStatementsSuccess | MsgError>>;

/** Selectable variant names for pension-statements. */
export type PensionStatementsVariantName =
  keyof typeof PENSION_STATEMENTS_VARIANTS;
