import { RpcResponse } from "../../types";

export const GET_EMPLOYEE_LEAVE_DETAILS: RpcResponse[] = [
  {
    success_flag: true,
    status_code: "200",
    message: "Success",
    data: [
      {
        from_dt: "25-04-2027",
        from_dt1: "2027-04-28",
        leave_cd: "COM",
        leave_desc: "Commuted Leave",
        no_days: "15",
        order_dt: "05/05/2022",
        order_dt1: "2022-05-05",
        reason_for_leave: "Any Personal Work/problem",
        to_dt: "09-05-2028",
        to_dt1: "2028-05-09",
        verify_flg_desc: "Verified",
      },
      {
        from_dt: "01-06-2023",
        from_dt1: "2023-06-01",
        leave_cd: "EL",
        leave_desc: "Earned Leave",
        no_days: "30",
        order_dt: "26/05/2023",
        order_dt1: "2023-05-26",
        reason_for_leave: "Any Personal Work/problem",
        to_dt: "30-06-2023",
        to_dt1: "2023-06-30",
        verify_flg_desc: "Verified",
      },
      {
        from_dt: "04-05-2026",
        from_dt1: "2026-05-04",
        leave_cd: "COM",
        leave_desc: "Commuted Leave",
        no_days: "30",
        order_dt: "25/05/2026",
        order_dt1: "2026-05-25",
        reason_for_leave: "Any Personal Work/problem",
        to_dt: "02-06-2026",
        to_dt1: "2026-06-02",
        verify_flg_desc: "Verified",
      },
      {
        leave_cd: "COM",
        leave_desc: "Commuted Leave",
        no_days: "15",
        order_dt: "05/05/2022",
        order_dt1: "2022-05-05",
        from_dt: "25-04-2022",
        from_dt1: "2022-04-25",
        to_dt: "09-05-2022",
        to_dt1: "2022-05-09",
        reason_for_leave: "Any Personal Work/problem",
        verify_flg_desc: "Verified",
      },
      {
        leave_cd: "EL",
        leave_desc: "Earned Leave",
        no_days: "30",
        order_dt: "26/05/2023",
        order_dt1: "2023-05-26",
        from_dt: "01-06-2023",
        from_dt1: "2023-06-01",
        to_dt: "30-06-2023",
        to_dt1: "2023-06-30",
        reason_for_leave: "Family Vacation",
        verify_flg_desc: "Verified",
      },
      {
        leave_cd: "HPL",
        leave_desc: "Half Pay Leave",
        no_days: "5",
        order_dt: "18/06/2026",
        order_dt1: "2026-06-18",
        from_dt: "27-06-2026",
        from_dt1: "2026-06-27",
        to_dt: "01-07-2026",
        to_dt1: "2026-07-01",
        reason_for_leave: "Medical Appointment",
        verify_flg_desc: "Pending",
      },
      {
        leave_cd: "CL",
        leave_desc: "Casual Leave",
        no_days: "2",
        order_dt: "24/06/2026",
        order_dt1: "2026-06-24",
        from_dt: "26-06-2026",
        from_dt1: "2026-06-26",
        to_dt: "27-06-2026",
        to_dt1: "2026-06-27",
        reason_for_leave: "Personal Work",
        verify_flg_desc: "Verified",
      },
      {
        leave_cd: "EL",
        leave_desc: "Earned Leave",
        no_days: "3",
        order_dt: "10/06/2026",
        order_dt1: "2026-06-10",
        from_dt: "15-06-2026",
        from_dt1: "2026-06-15",
        to_dt: "17-06-2026",
        to_dt1: "2026-06-17",
        reason_for_leave: "Family Function",
        verify_flg_desc: "Rejected",
      },
      {
        leave_cd: "SL",
        leave_desc: "Sick Leave",
        no_days: "1",
        order_dt: "25/06/2026",
        order_dt1: "2026-06-25",
        from_dt: "30-06-2026",
        from_dt1: "2026-06-30",
        to_dt: "30-06-2026",
        to_dt1: "2026-06-30",
        reason_for_leave: "Fever",
        verify_flg_desc: "Pending",
      },
    ],
  },
];

export const GET_EMPLOYEE_LEAVE_DETAILS_DETAILS: RpcResponse[] = [
  {
    success_flag: true,
    status_code: "200",
    message: "Success",
    data: {
      leave_cd: "EL",
      leave_desc: "Earned Leave",
      no_days: "3",
      order_dt: "10/06/2026",
      order_dt1: "2026-06-10",
      from_dt: "15-06-2026",
      from_dt1: "2026-06-15",
      to_dt: "17-06-2026",
      to_dt1: "2026-06-17",
      reason_for_leave: "Family Function",
      verify_flg_desc: "Pending",
      leave_reason_cd: "SL",
      closing_bal: 100,
      closing_bal_as_on: "2022-04-25",
      leave_type: "EL",
      no_days_credited: 15,
      opening_bal: 85,
      remarks: "",
      reason_for_rejection: "Rejected",
    },
  },
];

export const GET_LEAVES_REASON: RpcResponse[] = [
  {
    success_flag: true,
    status_code: "200",
    message: "Success",
    data: [
      { code_text: "Self-illness", code_value: "1" },
      { code_text: "Any Family Members Illness", code_value: "2" },
      { code_text: "For Self Department Exam", code_value: "3" },
      { code_text: "Childrens Exam", code_value: "4" },
      { code_text: "For Taking L.t.c", code_value: "5" },
      { code_text: "Maharashtra Dharshan Concession", code_value: "6" },
      { code_text: "Death Of Any Family Members", code_value: "7" },
      { code_text: "Self Marriage", code_value: "8" },
      { code_text: "Marriage Of Any Family Member", code_value: "9" },
      { code_text: "Any Personal Work/problem", code_value: "10" },
      { code_text: "For Any Religious Ceremony", code_value: "11" },
      { code_text: "School/college Admission Of Dependant", code_value: "12" },
      { code_text: "Other Reason", code_value: "13" },
    ],
  },
];

export const GET_LEAVES_TYPE: RpcResponse[] = [
  {
    success_flag: true,
    status_code: "200",
    message: "Success",
    data: [
      { leave_cd: "COM", leave_desc: "Commuted Leave" },
      { leave_cd: "LND", leave_desc: "Leave Not Due" },
      { leave_cd: "EOL", leave_desc: "Extraordinary Leave" },
      { leave_cd: "LPA", leave_desc: "Leave to Prob/Apprentice" },
      { leave_cd: "EL", leave_desc: "Earned Leave" },
      { leave_cd: "HPL", leave_desc: "Half Pay Leave" },
      { leave_cd: "ML", leave_desc: "Maternity Leave" },
      { leave_cd: "SL", leave_desc: "Study Leave" },
      { leave_cd: "WPL", leave_desc: "Without Pay Leave" },
      { leave_cd: "PL", leave_desc: "Paternity Leave" },
    ],
  },
];

export const INSERT_UPDATE_LEAVE: RpcResponse[] = [
  {
    success_flag: true,
    status_code: "200",
    message: "Success",
  },
];
